// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5GlrXJQ_XFAc3_Gf1Iylm5cW8yGDwUw',
    appId: '1:646434709850:web:685f83e51ff854da4ad363',
    messagingSenderId: '646434709850',
    projectId: 'android-ecommerce-5db73',
    authDomain: 'android-ecommerce-5db73.firebaseapp.com',
    storageBucket: 'android-ecommerce-5db73.firebasestorage.app',
    measurementId: 'G-TMNCV23M3W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgbh7H7hssKPH_P2IFcIQgUCJpIm55Lg',
    appId: '1:646434709850:android:aaa3d330e1d8eba34ad363',
    messagingSenderId: '646434709850',
    projectId: 'android-ecommerce-5db73',
    storageBucket: 'android-ecommerce-5db73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeOzOX5FxJ75tRf9d8W50mB2KyuC5WLIY',
    appId: '1:646434709850:ios:8b1ee439cb4352184ad363',
    messagingSenderId: '646434709850',
    projectId: 'android-ecommerce-5db73',
    storageBucket: 'android-ecommerce-5db73.firebasestorage.app',
    iosBundleId: 'com.example.wildfit.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeOzOX5FxJ75tRf9d8W50mB2KyuC5WLIY',
    appId: '1:646434709850:ios:358fb2c1fab53a5e4ad363',
    messagingSenderId: '646434709850',
    projectId: 'android-ecommerce-5db73',
    storageBucket: 'android-ecommerce-5db73.firebasestorage.app',
    iosBundleId: 'com.example.wildfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs5GlrXJQ_XFAc3_Gf1Iylm5cW8yGDwUw',
    appId: '1:646434709850:web:c6fbec5e900d16984ad363',
    messagingSenderId: '646434709850',
    projectId: 'android-ecommerce-5db73',
    authDomain: 'android-ecommerce-5db73.firebaseapp.com',
    storageBucket: 'android-ecommerce-5db73.firebasestorage.app',
    measurementId: 'G-S9288K7MC0',
  );
}
